allowBuilds:
  netim2-shared: true
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/37fc594be3d41ec7c50c6d5b27c129fc4fb6ab87: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/3ac2cef7b7d81b1e79429738bdd5f961bf089d27: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/5c17f606c7a98ed7c9c01358cacc8fc1ddb28bc0: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/666c40c63139f827fe60e195acab5155c89541d1: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/7a3793928290b326f088bef8f95c6516ab75295b: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/b91ff6243873e28bf71c20d43806c6faba6340fe: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/c8358efa5f7e901d9b45f94ca5ac147839af97aa: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/dddbb052a803dcdfdd976656f69fc9d0fccecb04: false
  netim2-shared@https://codeload.github.com/FrancoMiralles98/netim2-shared/tar.gz/debd7db8ba36db56b6e204d2b1c09ec2ec22d1fb: false
