import { allFullNameBonusList, type BonusRefKeys } from "netim2-shared";

export const BONUS_FULL_NAME_BY_REF = {
    chances_raros: allFullNameBonusList.AUMENTO_DE_OBJETOS_RAROS,
    robo_vida: allFullNameBonusList.ROBO_DE_VIDA,
    vampirismo_hechizo: allFullNameBonusList.VAMPIRISMO_DE_HECHIZO,
    habilidad: allFullNameBonusList.DAÑO_DE_HABILIDAD,
    media: allFullNameBonusList.DAÑO_DE_MEDIA,
    def: allFullNameBonusList.DEFENSA,
    def_campana: allFullNameBonusList.DEFENSA_CAMPANA,
    def_desmayo: allFullNameBonusList.DEFENSA_CONTRA_DESMAYO,
    def_retardo: allFullNameBonusList.DEFENSA_CONTRA_RETARDO,
    def_daga: allFullNameBonusList.DEFENSA_DAGA,
    def_dos_manos: allFullNameBonusList.DEFENSA_DOS_MANOS,
    def_espada: allFullNameBonusList.DEFENSA_ESPADA,
    def_fan: allFullNameBonusList.DEFENSA_FAN,
    DEX: allFullNameBonusList.DEX,
    INT: allFullNameBonusList.INT,
    STR: allFullNameBonusList.STR,
    VIT: allFullNameBonusList.VIT,
    hp: allFullNameBonusList.MAX_HP,
    regen_hp: allFullNameBonusList.REGENERACION_DE_HP,
    chances_yang: allFullNameBonusList.FRECUENCIA_DE_YANG,
    chances_objetos: allFullNameBonusList.PROB_DE_CAER_MAS_OBJETOS,
    chances_exp: allFullNameBonusList.PROB_DE_OBTENER_BONUS_DE_EXP,
    bonus_yang: allFullNameBonusList.BONUS_YANG,
    bonus_exp: allFullNameBonusList.BONUS_EXP,
    time_reduction: allFullNameBonusList.TIME_REDUCTION,
    veneno: allFullNameBonusList.OPCION_DE_ENVENENAMIENTO,
    incendio: allFullNameBonusList.OPCION_DE_INCENDIO,
    sangrado: allFullNameBonusList.OPCION_DE_SANGRADO,
    bonus_veneno: allFullNameBonusList.BONUS_VENENO,
    bonus_fuego: allFullNameBonusList.BONUS_INCENDIO,
    bonus_sangrado: allFullNameBonusList.BONUS_SANGRAD,
    critico: allFullNameBonusList.PROB_DE_GOLPES_CRITICOS,
    daño_critico: allFullNameBonusList.DAÑO_CRITICO,
    penetracion: allFullNameBonusList.PROB_DE_GOLPES_DE_PENETRACION,
    penetracion_habilidad: allFullNameBonusList.PENETRACION_HABILIDAD,
    retardo: allFullNameBonusList.PROB_DE_RETARDO,
    desmayo: allFullNameBonusList.OPCION_DE_DESMAYO,
    corta_curacion: allFullNameBonusList.CORTA_CURACION,
    ad: allFullNameBonusList.VALOR_DE_ATAQUE,
    ap: allFullNameBonusList.VALOR_DE_ATAQUE_MAGICO,
    animales:  allFullNameBonusList.FUERZA_CONTRA_ANIMALES,
    bloquear_ataques:  allFullNameBonusList.PROB_DE_BLOQUEAR_ATAQUES_BASICOS,
    bonus_estado: allFullNameBonusList.BONUS_ESTADO,
    chaman:  allFullNameBonusList.FUERZA_CONTRA_CHAMANES,
    damage_taken:  allFullNameBonusList.REGENERACION_DE_HP

} satisfies Record<BonusRefKeys, allFullNameBonusList>