import type { BonusRefKeys } from "netim2-shared";

export const BONUS_INFO: Record<BonusRefKeys, string> = {
    ad: 'Determina el daño de los ataques básicos y aumenta el daño de las habilidades de daño físico que escalan con este valor.',
    animales: 'Aumenta el daño de todas las fuentes a enemigos de tipo Animales.',
    ap: 'Aumenta el daño de las habilidades de daño mágico que escalan con este valor.',
    bloquear_ataques: 'Determina las chances de bloquear ataques básicos, anulando el daño recibido.',
    bonus_estado: 'Aumenta el daño de todos los efectos de estados: Veneno, Fuego y Sangrado.',
    bonus_exp: 'Aumenta la experiencia recibida al derrotar mobs.',
    bonus_fuego: 'Aumenta el daño del efecto de Fuego.',
    bonus_sangrado: 'Aumenta el daño del efecto de Sangrado.',
    bonus_veneno: 'Aumenta el daño del efecto de Veneno.',
    bonus_yang: 'Aumenta el Yang ganado al derrotar mobs.',
    chaman: 'Aumenta el daño de todas las fuentes a las razas de tipo Chaman',
    chances_exp: 'Determina las chances de conseguir un bonus de EXP al derrotar un mob.',
    chances_objetos: 'Aumenta las chances de conseguir objetos al derrotar mobs.',
    chances_raros: 'Aumenta las chances de conseguir objetos más raros al derrotar mobs.',
    chances_yang: 'Aumenta las chances de obtener más yang al derrotar mobs.',
    corta_curacion: 'Determina las chances de reducir cualquier curación del enemigo en 1 turno.',
    critico: 'Determina las chances de causar daño critico, tanto en habilidades como ataques básicos',
    damage_taken: 'Reduccion o Aumento del daño recibido de todas las fuentes.',
    daño_critico: 'Determina el aumento del daño a la hora de realizar un critico.',
    def: 'La defensa plana reduce el daño recibido de ataques básicos.',
    def_campana: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_daga: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_chaman: 'Reduce el daño recibido de todas las fuentes provenientes de un Chaman',
    def_desmayo: 'Determina las chances de resistir y no ser afectado por el efecto.',
    def_dos_manos: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_espada: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_fan: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_flecha: 'Reduce el daño recibido de ataques básicos y habilidades de daño físico realizadas con esta arma.',
    def_guerrero: 'Reduce el daño recibido de todas las fuentes provenientes de un Guerrero',
    def_hab: 'Reduce el daño recibido de cualquier habilidad. ',
    def_incendio: 'Reduce el daño recibido del efecto Incendio',
    def_magia: 'Reduce el daño de Habilidades de daño mágico',
    def_media: 'Reduce el daño recibido de ataques basicos.',
    def_ninja: 'Reduce el daño recibido de todas las fuentes provenientes de un Ninja',
    def_retardo: 'Determina las chances de resistir y no ser afectado por el efecto.',
    def_sangrado: 'Reduce el daño recibido del efecto Sangrado',
    def_sura: 'Reduce el daño recibido de todas las fuentes provenientes de un Sura',
    def_veneno: 'Reduce el daño recibido del efecto Veneno',
    demonios: 'Aumenta el daño de todas las fuentes a enemigos de tipo Demonios.',
    desmayo: 'Determina las chances de que los ataques básicos ocasionen este efecto.',
    DEX: 'DEX',
    doble_golpe: 'Las chances de que en un turno se realice un ataque básico adicional.',
    duracion_estado: 'Aumenta la duración de los efectos de estados.',
    esquivar_ataques: 'Determina las chances de esquivar ataques básicos, anulando su daño.',
    guerrero: 'Aumenta el daño de todas las fuentes a las razas de tipo Guerrero',
    habilidad: 'Aumenta el daño de todas las habilidades.',
    hp: 'Determina la vida máxima del personaje.',
    incendio: 'Determina las chances de que los ataques básicos ocasionen este efecto.',
    INT: 'INT',
    media: 'Aumenta el daño de los ataques básicos.',
    medio_humanos: 'Aumenta el daño de todas las fuentes a enemigos de tipo Medio Humanos.',
    misticos: 'Aumenta el daño de todas las fuentes a enemigos de tipo Misticos.',
    monstruos: 'Aumenta el daño de todas las fuentes a enemigos de tipo Monstruos.',
    ninja: 'Aumenta el daño de todas las fuentes a las razas de tipo Ninja',
    orcos: 'Aumenta el daño de todas las fuentes a enemigos de tipo Orcos.',
    penetracion: 'Determina las chances de que los ataques básicos penetren la armadura del enemigo, reduciendo porcentualmente sus defensas.',
    penetracion_habilidad: 'Determina el porcentaje de reducción de defensas del enemigo al realizar la habilidad.',
    reflectar: 'Determina las chances de reflectar tanto ataques básicos como habilidades, haciendo que reciba parte del daño recibido.',
    regen_hp: 'Determina la cantidad de vida, en base a su vida máxima, que se recupera por turno.',
    retardo: 'Determina las chances de que los ataques básicos ocasionen este efecto.',
    robo_vida: 'Determina el porcentaje de vida a recuperar en base al daño realizado de ataques básicos.',
    sangrado: 'Determina las chances de que los ataques básicos ocasionen este efecto.',
    STR: 'STR',
    sura: 'Aumenta el daño de todas las fuentes a las razas de tipo Sura',
    time_reduction: 'Determina el porcentaje de reduccion de tiempo de espera para volver a pelear.',
    va: 'Determina la velocidad de ataque de los ataques básicos aumentando las chances de ocasionar ataques dobles',
    vampirismo_hechizo: 'Determina el porcentaje de vida a recuperar en base al daño realizado de cualquier habilidad.',
    veneno: 'Determina las chances de que los ataques básicos ocasionen este efecto.',
    vh: 'Determina el porcentaje de reduccion de tiempo de espera para volver a usar las habilidades.',
    VIT: 'VIT',
    vm: 'Determina la velocidad de moviemiento del personaje, aumentando las chances de esquivar ataques.'
}